# Build config
gems:
    - jemoji
    - jekyll-paginate

url: 'http://vanbosse.be'
baseurl: ''
permalink: /:year/:month/:day/:title/

paginate: 5
paginate_path: "/page/:num"

# Site config
title: 'Jeroen Van den Bossche'
description: >
    Web developer, soccer enthusiast and cyclist in his spare time.
    Blogging about whatever comes to mind worth blogging about.
name: 'Jeroen Van den Bossche'
author: 'Jeroen Van den Bossche'
email: vanbosse.jeroen@gmail.com
author_image: '/assets/images/author.png'
logo: '/assets/images/author.png'
cover: '/assets/images/background.jpg'

# Social
twitter_handle: '@vanbosse'
disqus: vanbosse
social:
    - icon: twitter
      url: https://twitter.com/vanbosse
      desc: Follow me on twitter
      share_url: http://twitter.com/share
      share_title: ?text=
      share_link: '&amp;url='

    - icon: github
      url: https://github.com/vanbosse
      desc: Follow me on github
      share_url:
      share_title:
      share_link:

    - icon: instagram
      url: https://instagram.com/vanbosse
      desc: Look through my Instagram photos
      share_url:
      share_title:
      share_link:

    - icon: bicycle
      url: https://www.strava.com/athletes/276614
      desc: See my rides on Strava
      share_url:
      share_title:
      share_link:
